export const CATEGORIES = {
  FUNDAMENTOS:  { key: 'FUNDAMENTOS',  label: 'Fundamentos',          color: '#818CF8' },
  PATRONES:     { key: 'PATRONES',     label: 'Patrones y Arquitectura', color: '#34D399' },
  DEUDA:        { key: 'DEUDA',        label: 'Cambio y Deuda',        color: '#FBBF24' },
  TESTING:      { key: 'TESTING',      label: 'Testing',               color: '#F472B6' },
  SISTEMAS:     { key: 'SISTEMAS',     label: 'Sistemas y Ops',        color: '#38BDF8' },
  COLABORACION: { key: 'COLABORACION', label: 'Colaboración',          color: '#C084FC' },
  SISTEMICO:    { key: 'SISTEMICO',    label: 'Pensamiento Sistémico', color: '#FB923C' },
};

export const concepts = [
  // ─── Fundamentos ───────────────────────────────────────
  {
    id: 'solid',
    category: 'FUNDAMENTOS',
    icon: '🏛️',
    title: 'SOLID',
    description: 'Cinco principios de diseño orientado a objetos: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation y Dependency Inversion. Definen cómo deben relacionarse clases y módulos.',
    solves: 'Clases con demasiadas responsabilidades, código que rompe al cambiar, dependencias imposibles de mockear y módulos que no se pueden reutilizar en otro contexto.',
  },
  {
    id: 'dry-yagni-kiss',
    category: 'FUNDAMENTOS',
    icon: '✂️',
    title: 'DRY / YAGNI / KISS',
    description: 'Tres principios complementarios: Don\'t Repeat Yourself (una sola fuente de verdad), You Aren\'t Gonna Need It (no construyas lo que no necesitas hoy), Keep It Simple (la solución más simple es la correcta).',
    solves: 'Duplicación que genera inconsistencias, sobreingeniería prematura y código tan abstracto que nadie entiende qué hace sin trazar la ejecución entera.',
  },
  {
    id: 'clean-code',
    category: 'FUNDAMENTOS',
    icon: '✨',
    title: 'Clean Code',
    description: 'Conjunto de prácticas popularizadas por Robert Martin: nombres descriptivos que eliminan la necesidad de comentarios, funciones pequeñas con una sola responsabilidad y ausencia de código que explica código malo.',
    solves: 'Código que tarda horas en entenderse, revisiones de PR interminables y la sensación de que hay que reescribir todo antes de poder modificar algo.',
  },
  {
    id: 'cohesion-acoplamiento',
    category: 'FUNDAMENTOS',
    icon: '🔗',
    title: 'Cohesión y Acoplamiento',
    description: 'Cohesión alta: cada módulo hace una sola cosa bien. Bajo acoplamiento: los módulos dependen entre sí lo mínimo posible, idealmente a través de abstracciones. Son las dos caras del mismo principio de diseño.',
    solves: 'Cambios en cascada donde tocar un módulo rompe cinco más, imposibilidad de probar en aislamiento y arquitecturas que se vuelven más rígidas con cada nueva feature.',
  },
  // ─── Patrones y Arquitectura ───────────────────────────
  {
    id: 'design-patterns',
    category: 'PATRONES',
    icon: '🧩',
    title: 'Design Patterns (GoF)',
    description: 'Catálogo de 23 soluciones reutilizables a problemas recurrentes de diseño: Singleton, Factory, Observer, Strategy, Decorator, Command, etc. Son un vocabulario compartido para comunicar intención de diseño.',
    solves: 'Reinventar soluciones que ya existen, falta de lenguaje común en el equipo y arquitecturas ad-hoc difíciles de explicar o extender sin leer todo el código.',
  },
  {
    id: 'arquitecturas',
    category: 'PATRONES',
    icon: '🏗️',
    title: 'Arquitecturas de Software',
    description: 'Estilos estructurales para organizar sistemas completos: Layered (capas), Hexagonal/Ports & Adapters, Clean Architecture, Event-Driven. Cada uno define cómo fluyen las dependencias y dónde vive la lógica de negocio.',
    solves: 'Lógica de negocio mezclada con infraestructura, acoplamiento directo con frameworks y bases de datos, e imposibilidad de probar el dominio sin levantar todo el sistema.',
  },
  {
    id: 'ddd',
    category: 'PATRONES',
    icon: '🗺️',
    title: 'Domain-Driven Design',
    description: 'Metodología que centra el diseño en el dominio de negocio. Introduce Ubiquitous Language, Bounded Contexts, Aggregates, Entities y Value Objects para crear modelos que reflejan la realidad del negocio.',
    solves: 'Modelos anémicos que no representan el negocio, confusión terminológica entre devs y stakeholders, y sistemas donde todo depende de todo porque no hay boundaries claros.',
  },
  // ─── Cambio y Deuda ────────────────────────────────────
  {
    id: 'refactoring',
    category: 'DEUDA',
    icon: '🔨',
    title: 'Refactoring',
    description: 'Proceso de reestructurar código existente sin cambiar su comportamiento externo. Incluye técnicas catalogadas por Martin Fowler: Extract Method, Replace Conditional with Polymorphism, Introduce Parameter Object, entre otras.',
    solves: 'Deuda técnica que se acumula silenciosamente, código que nadie quiere tocar y la tendencia destructiva de reescribir en vez de mejorar incrementalmente con tests de respaldo.',
  },
  {
    id: 'deuda-tecnica',
    category: 'DEUDA',
    icon: '💳',
    title: 'Deuda Técnica',
    description: 'Metáfora de Ward Cunningham: el código que se escribe rápido o con atajos genera interés que se paga luego en mayor costo de mantenimiento. Existen cuatro cuadrantes según sea deliberada/inadvertida y prudente/imprudente.',
    solves: 'Incapacidad de cuantificar trabajo técnico frente a features, la sensación de que todo se mueve cada vez más lento y equipos que no pueden sostener su propia velocidad de entrega.',
  },
  {
    id: 'feature-flags',
    category: 'DEUDA',
    icon: '🚩',
    title: 'Feature Flags',
    description: 'Técnica para activar o desactivar funcionalidades en producción sin hacer deploy. Permite trunk-based development, canary releases, rollbacks instantáneos y A/B testing desacoplado del ciclo de releases.',
    solves: 'Branches de larga vida que generan conflictos traumáticos, incapacidad de desplegar con frecuencia y el miedo a "meter" features incompletas en main.',
  },
  // ─── Testing ───────────────────────────────────────────
  {
    id: 'piramide-testing',
    category: 'TESTING',
    icon: '🔺',
    title: 'Pirámide de Testing',
    description: 'Modelo que define la proporción óptima de tests: muchos unit tests (rápidos, baratos), menos de integración (más lentos, más realistas), pocos e2e (lentos, costosos de mantener). Cada nivel tiene distinto trade-off.',
    solves: 'Suites de CI que tardan 45 minutos, tests e2e frágiles que fallan por cualquier cambio de UI, falsa sensación de cobertura y tests que nadie ejecuta localmente.',
  },
  {
    id: 'tdd',
    category: 'TESTING',
    icon: '🔄',
    title: 'TDD',
    description: 'Test-Driven Development: escribir el test antes que el código de producción. El ciclo Red-Green-Refactor guía el diseño emergente y garantiza que cada línea de código tiene razón de existir.',
    solves: 'APIs mal diseñadas que solo se descubren al usarlas, código difícil de testear por sus dependencias implícitas y la tendencia a agregar features sin saber si la base funciona.',
  },
  {
    id: 'test-doubles',
    category: 'TESTING',
    icon: '🎭',
    title: 'Test Doubles',
    description: 'Sustitutos de dependencias reales en tests: Stubs (devuelven valores fijos), Mocks (verifican interacciones), Fakes (implementaciones simplificadas funcionales) y Spies (registran llamadas sin cambiar comportamiento).',
    solves: 'Tests lentos que llaman a la base de datos real, imposibilidad de reproducir casos de error de infraestructura y tests que fallan por razones completamente ajenas al código bajo prueba.',
  },
  // ─── Sistemas y Ops ────────────────────────────────────
  {
    id: 'observabilidad',
    category: 'SISTEMAS',
    icon: '🔭',
    title: 'Observabilidad',
    description: 'Capacidad de entender el estado interno de un sistema a partir de sus outputs externos. Se construye sobre tres pilares: logs estructurados (qué pasó), métricas (cuánto) y trazas distribuidas (por dónde).',
    solves: 'Bugs en producción imposibles de reproducir localmente, la típica sesión de SSH y grep a ciegas, y sistemas distribuidos donde no sabes en qué servicio está fallando algo.',
  },
  {
    id: '12factor',
    category: 'SISTEMAS',
    icon: '📋',
    title: '12-Factor App',
    description: 'Metodología de Heroku para aplicaciones SaaS modernas: configuración en variables de entorno, dependencias declaradas explícitamente, procesos stateless, logs como streams, backing services intercambiables.',
    solves: 'Apps que solo funcionan "en mi máquina", configuración hardcodeada en el código, deploys frágiles y sistemas que no pueden escalar horizontalmente sin cirugía mayor.',
  },
  {
    id: 'concurrencia',
    category: 'SISTEMAS',
    icon: '⚡',
    title: 'Concurrencia',
    description: 'Ejecución de múltiples tareas que comparten recursos. Incluye race conditions, deadlocks, mutex, semáforos y modelos de alto nivel como el Actor Model o Communicating Sequential Processes (CSP).',
    solves: 'Bugs intermitentes que no se pueden reproducir, datos corruptos bajo carga concurrente y código que pasa todos los tests pero falla misteriosamente en producción con múltiples usuarios.',
  },
  // ─── Colaboración ──────────────────────────────────────
  {
    id: 'git-avanzado',
    category: 'COLABORACION',
    icon: '🌿',
    title: 'Git Avanzado',
    description: 'Más allá de commit y push: trunk-based development vs Gitflow, rebase interactivo, cherry-pick, bisect para encontrar bugs, y convenciones como Conventional Commits para historiales legibles.',
    solves: 'Historiales de commits que no cuentan nada, merges traumáticos de branches que vivieron semanas y la incapacidad de encontrar cuándo y por qué se introdujo un bug.',
  },
  {
    id: 'code-review',
    category: 'COLABORACION',
    icon: '👁️',
    title: 'Code Review',
    description: 'Proceso estructurado de revisión entre pares: qué revisar (diseño, legibilidad, tests, edge cases, seguridad), cómo dar feedback constructivo orientado al código y no a la persona, y cómo recibirlo sin ego.',
    solves: 'Bugs que llegan a producción, conocimiento silado en una sola persona, inconsistencia de estilo y equipos donde nadie aprende del código de los demás porque los PR se aprueban sin leer.',
  },
  {
    id: 'adrs',
    category: 'COLABORACION',
    icon: '📝',
    title: 'ADRs',
    description: 'Architecture Decision Records: documentos cortos que registran una decisión técnica, su contexto, las alternativas consideradas y las consecuencias esperadas. Viven junto al código en el repositorio.',
    solves: 'Decisiones de diseño que nadie recuerda por qué se tomaron, equipos nuevos que repiten discusiones ya resueltas y refactors que rompen invariantes implícitas del sistema.',
  },
  // ─── Pensamiento Sistémico ─────────────────────────────
  {
    id: 'tradeoffs',
    category: 'SISTEMICO',
    icon: '⚖️',
    title: 'Trade-offs Explícitos',
    description: 'Disciplina de evaluar soluciones no en términos de "correcta vs incorrecta" sino de compensaciones entre atributos: performance vs legibilidad, consistencia vs disponibilidad, velocidad de desarrollo vs seguridad.',
    solves: 'Debates técnicos que no llegan a ningún lado, adopción de tecnologías por moda y arquitecturas que optimizan una dimensión a expensas ocultas e implícitas de las demás.',
  },
  {
    id: 'complejidad',
    category: 'SISTEMICO',
    icon: '🧶',
    title: 'Complejidad Esencial vs Accidental',
    description: 'Distinción de Moseley & Marks (Out of the Tar Pit): la complejidad esencial viene del problema en sí y no se puede eliminar. La accidental la introduce el propio código con abstracciones innecesarias, frameworks e indirección.',
    solves: 'Sistemas imposibles de mantener no porque el dominio sea difícil, sino porque el código acumuló capas de complejidad que no aportan nada al problema que se supone que resuelven.',
  },
  {
    id: 'diseno-para-el-cambio',
    category: 'SISTEMICO',
    icon: '🌱',
    title: 'Diseño para el Cambio',
    description: 'El software siempre va a cambiar, por lo que el diseño debe anticipar extensión sin modificación (Open/Closed), interfaces estables con implementaciones intercambiables y bajo acoplamiento estructural en todos los niveles.',
    solves: 'El miedo a tocar código existente, nuevas features que requieren cambios en cascada a través de toda la codebase y arquitecturas que se vuelven más rígidas e impredecibles con cada iteración.',
  },
];
